blank_issues_enabled: true
contact_links:
  - name: GitHub Primer/Figma Support (internal)
    url: https://github.slack.com/archives/C049REXSRBQ
    about: If you have questions please join the slack #primer-figma.
