# Name of the action visible in the action overview
name: Figma release
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    type: figma-release

jobs:
  build:
    env:
      BRANCH: 'figma-${{ fromJSON(github.event.client_payload.releaseJson).fileInfo.fileName }}'
      LIBRARY: '${{fromJSON(github.event.client_payload.releaseJson).fileInfo.fileName}}'
      PR_BODY: 'Merge this to create a new release for ${{fromJSON(github.event.client_payload.releaseJson).fileInfo.fileName}}.'
      PR_TITLE: 'Release for ${{fromJSON(github.event.client_payload.releaseJson).fileInfo.fileName}}'
    # the name for the entire job
    name: Create new primer/figma release
    # we run this on ubuntu, leave this alone, if you don't have a good reason to change it
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm i

      - name: save API response to temporary json
        run: |
          echo '${{ github.event.client_payload.releaseJson }}' > "temp-api-response.json"

      - id: create_changeset
        name: create changeset
        run: |
          npx ts-node --transpile-only .github/actions/create-changeset.ts

      - name: commit to base branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "added changeset for ${{ env.LIBRARY }}"
          add: ".changeset"
          new_branch: ${{env.BRANCH}}

      - name: create pull request
        run: gh pr edit ${{ env.BRANCH }} -b '${{ env.PR_BODY }}' -t '${{ env.PR_TITLE }}'  && gh pr reopen ${{ env.BRANCH }} || gh pr create --fill -B main -H ${{ env.BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}